//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Less.API.NetFramework.KakaoBotAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Less.API.NetFramework.KakaoBotAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; 금지어 및 대체어 목록을 &quot;[Contents]&quot; 아래에 입력합니다.
        ///; (예: 금지어 = 대체어)
        ///; 세미콜론(;)으로 시작하는 문장은 주석으로 인식합니다.
        ///[Contents].
        /// </summary>
        internal static string bot_limitedWords {
            get {
                return ResourceManager.GetString("bot_limitedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; 바로가기 명령어 (줄인 명령어 = 실제 명령어)
        ///; 예시 : !포켓몬 1 = !퀴즈 초성 포켓몬-1세대
        ///; 영어의 경우 대소문자를 구분하지 않습니다.
        ///; 세미콜론(;)으로 시작하는 문장은 주석으로 인식합니다..
        /// </summary>
        internal static string cmd_shortcuts {
            get {
                return ResourceManager.GetString("cmd_shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 퀴즈봇을 돌리기 위해서는, 반드시 해당 주제에 대한 퀴즈 데이터 폴더 및 내부 파일이 존재해야 합니다.
        ///폴더 및 파일을 추가하는 방법은 아래와 같습니다.
        ///
        ///◎ 폴더 생성
        ///- data/quiz 경로에 폴더를 하나 생성합니다.
        ///(폴더 이름은 아무렇게나 해도 됩니다)
        ///
        ///◎ settings.ini 파일 추가
        ///생성한 폴더 내에 settings.ini라는 이름으로 파일을 생성합니다. 인코딩은 유니코드(= UTF-16)로 합니다.
        ///
        ///파일 최상단에 &quot;[Settings]&quot; 입력 (ini 파일의 섹션 값)
        ///
        ///- &quot;quizType = &quot; 뒤에 퀴즈 유형 입력 (&quot;일반&quot; 또는 &quot;초성&quot;)
        ///
        ///- &quot;mainSubject = &quot; 뒤에 주제 입력
        ///
        ///- &quot;childSubjects = &quot; 뒤에 하위주제의 목록을 쉼표(,)로 구분하여 입력합니다. (하위주제가 없으면 입력하지 않아도 됩니다.)
        ///
        ///- &quot;isCaseSensitive = &quot; 뒤에 true 또는 false 입력
        ///(만약 정답에 알파벳이 포함되어 있는 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string how_to_add_quiz_subjects {
            get {
                return ResourceManager.GetString("how_to_add_quiz_subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; 여기에는 퀴즈 시작 전에 나오는 알림 메시지를 작성합니다.
        ///; 세미콜론(;)으로 시작하는 문장은 주석으로 인식합니다.
        ///공지 파일을 수정하여 유저들과 최신 소식을 공유해보세요..
        /// </summary>
        internal static string quiz_notice {
            get {
                return ResourceManager.GetString("quiz_notice", resourceCulture);
            }
        }
    }
}
